package com.document;

import java.io.FileWriter;
import java.io.IOException;

public class PDFDocumentGenerator {
    public static void generatePDF(Document document, String outputPath) throws IOException {
        try (FileWriter writer = new FileWriter(outputPath)) {
            writer.write("%PDF-1.4\n"); 
            writer.write("% This is a mock PDF file generated by the Document Generator\n\n");
            
            writer.write("Document Title: " + document.getTitle() + "\n");
            writer.write("Author: " + document.getAuthor() + "\n");
            writer.write("Student ID: " + document.getStudentId() + "\n\n");
            
            writer.write("--- Content ---\n\n");
            
            for (DocumentElement element : document.getElements()) {
                writer.write("[" + element.getType() + "] " + element.getContent() + "\n\n");
            }
        }
    }
}
